name: Test code

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 12
      matrix:
        plugin: [femwell, gmsh, meow, sax, tidy3d, klayout, vlsir]
        os: [ubuntu-latest]
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: |
          uv venv -p ${{ matrix.python-version }}
          uv pip install .[${{ matrix.plugin }},dev] setuptools
      - name: Test pre-commit hooks
        run: |
          uv run pre-commit run --files gplugins/${{ matrix.plugin }}/*

  test_code:
    needs: pre-commit
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 24
      matrix:
        plugin: [femwell, gmsh, meow, sax, tidy3d, klayout, vlsir]
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        python-version: [3.11] #, 3.13]
        exclude:
          - plugin: femwell
            os: macos-latest
          - plugin: femwell
            os: windows-latest
          - plugin: sax
            python-version: 3.13

    name: Test ${{ matrix.plugin }} ${{ matrix.os }} ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: env
          use-mamba: true
          python-version: ${{ matrix.python-version }}
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - uses: astral-sh/setup-uv@v5
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install -y libglu1-mesa
      - name: Install dependencies
        run: |
          uv venv -p ${{ matrix.python-version }}
          uv pip install .[${{ matrix.plugin }},dev] setuptools
          make test-data
      - name: Test with pytest
        run: |
          uv run pytest gplugins/${{ matrix.plugin }}

  test_code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Install libglu1-mesa
        run: |
          sudo apt-get install -y libglu1-mesa
      - name: Install dependencies
        run: |
          make install test-data
      - name: Test with pytest
        run: |
          make cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
